wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/oldworld_framework.png
    fit_mode = cover
}

#wallpaper {
#    monitor = DP-2
#    path = ~/myFile2.jxl
#    fit_mode = cover
#}

#wallpaper {
#    monitor = 
#    path = ~/fallback.jxl
#    fit_mode = cover
#}

splash = false
