general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    inhibit_sleep = 3
}

# Lock after 3 minutes
listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

# Turn displays off 2 minutes after locking
listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Suspend after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend-then-hibernate
}
