wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/oldworld_framework.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:Acer Technologies KGB271U X1 2536015715W01
    path = ~/Pictures/Wallpapers/oldworld_1440.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:Acer Technologies KGB271U X1 45280269A4204
    path = ~/Pictures/Wallpapers/oldworld_1440.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/Pictures/Wallpapers/oldworld_1080.png
    fit_mode = cover
}

splash = false
